api-version: v3

# Server
server:
  port: 4885
  shutdown: graceful
  
# Spring boot
spring:
  application:
    name: "functional API"
  pid:
    file: functional-${spring.profiles.active}.pid
  profiles:
    active: "local"
  devtools:
    restart:
      enabled: true
    add-properties: true
  
# Log
logging:
  group:
    info-group: org.springframework, org.mybatis, io.swagger, org.mariadb.jdbc, org.springframework.web.reactive, reactor, reactor.netty
  level:
    root: debug
    info-group: info
  file:
    name: /data/logs/functional-app/functional-app.log
    max-size: 100MB
  logback:
    rollingpolicy:
      max-history: 30
      file-name-pattern: /data/logs/functional-app/%d{yyyy-MM}/functional-app.%d{yyyy-MM-dd}.%i.log
  program-access:
    level: none
    
# Swagger springdoc-ui Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 경로 => localhost:8000/webjars/swagger-ui.html
    enabled: true
    use-root-path: true
    tags-sorter: alpha
    doc-expansion: none
    groups-order: asc
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  packages-to-scan: com.func.functional
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

    
# Api-Server
api-server:
  servers:
    - name: holidayInfo
      domain: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService
      key: pO%2FiZd5X0eNFNWyEOKUcR2MYFgOZ%2Bud9als%2BkNiBu6FT5XqvHQ5sK1mW3zgtV%2BGWh%2BaMhfdaMHRzigZ7VtXNcQ%3D%3D
      endpoints:
        - endpointKey: getHoliDeInfo
          description: 국경일 정보조회
        - endpointKey: getRestDeInfo
          description: 공휴일 정보조회
        - endpointKey: getAnniversaryInfo
          description: 기념일 정보조회
        - endpointKey: get24DivisionsInfo
          description: 24절기 정보조회
        - endpointKey: getSundryDayInfo
          description: 잡절 정보조회